### ISSUE TITLE
Option to add links to divs without using inline text

### ISSUE THREAD

**Issue by discretize** [madou/armory-embeds#10]
Maybe rename/split up the _data-armory-inline-text_ attribute so it can be used on div-icons without a text next to it (cf. https://github.com/madou/armory-embeds/issues/9)

From the description:

>  data-armory-inline-text | string | no | Optional inline text that will be displayed to the right of the icon. You can pass in wiki to use a gw2 wiki URL, or pass in any other text that will be used as the link 

one would probably expect it to change the visible text, not the link

**Comment by madou** [comment]
this can't be done, the confusion will be fixed up though in #9
