### ISSUE TITLE
Language option is not working

### ISSUE THREAD

**Issue by okubiak** [madou/armory-embeds#12]
Adding 
```
<script>
document.GW2A_EMBED_OPTIONS = {
  lang: "fr"
};
</script>
```
is not working for inline text and tooltip.

However it seems to work for wiki base url

**Comment by okubiak** [comment]
Well after having restarted chrome, it seems to work again on https://madou.github.io/armory-embeds/?selectedKind=configuration&selectedStory=french&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel...
I'm closing the issue, sorry

**Comment by madou** [comment]
hello :)

yeah its a limitation with the embeds. it gets set on page load. so the example page only works if you refresh the page.

would be good to investigate later if we can get it working on the fly.

**Comment by okubiak** [comment]
The worst thing is that I'm fighting since yesterday to understand what's the issue on my forum, but it seems that it's just a cache issue with phpbb... :)
Thanks for your work!
