### ISSUE TITLE
Embeds container still displays an extra whitespace at the bottom

### ISSUE THREAD

**Issue by paulocf92** [madou/armory-embeds#14]
Could be a bug/unintended behavior. See [this example](https://jsfiddle.net/9xegLjg3/) (yellow represents whitespace, it doesn't blend nicely with border styling).

To solve this myself I [set line-height to 0](https://jsfiddle.net/7wy9arvw/) for all main container classes.

**Comment by madou** [comment]
line height 0 breaks other sites for inline text, need to investigate!
