### ISSUE TITLE
Display skill facts as ordered in-game

### ISSUE THREAD

**Issue by valento92** [madou/armory-embeds#15]
This would prompt some investigation. Right now you display them as they're pulled from the API, but that's not correct because in-game they seem to have a different prioritization. From [this example](https://jsfiddle.net/y73p661r/) you can see taunt at the end and some other things not correctly ordered.

My guess is that they start with damage, then immediately go to boons/conditions, then movement-affecting facts, then size facts, then the rest, but that's a wild guess. I have [asked this](https://github.com/arenanet/api-cdi/issues/581) to be fixed on their side too.

**Comment by madou** [comment]
Moved to the more appropriate repo: https://github.com/madou/armory-component-ui/issues/11
