### ISSUE TITLE
Shuttering? on hover info on Firefox

### ISSUE THREAD

**Issue by toligmueller** [madou/armory-embeds#17]
![2017-11-17 04_53_50-mesmer - vanilla shatter - metabattle guild wars 2 builds](https://user-images.githubusercontent.com/30302750/32928993-556eae06-cb55-11e7-93a5-bc38819d8e1f.png)

On Firefox 57 the Info about the item shutters, its not any of my extensions, it happens on all sites with armory, even my own. Also its not my PC same happens on Laptop and same for a Friend.

**Comment by madou** [comment]
hi there.

are you running windows?
does this happen all the time, or just sometimes?
at the time when running did you have a lot of tabs open?
anything else you think could be relevant?

it's an odd bug.

**Comment by DasReyko** [comment]
Windows 10 on latest build, it happens after hover and moving away from it (and moving the mouse around like crazy). 
I've test both, with much tabs open and only one with a site with armory. Since it's doesn't happen on Chrome or edge it could be how Firefox interprets css or js?
Also, even I am pretty sure that it's irrelevant butall machines used for testing were intel/NVIDIA.

I wish I could help more.

**Comment by Tolgon** [comment]
A person from my guild has reproduced this same bug on Firefox 58.0.1. Wasn't able to reproduce it on different browsers. Unfortunately I don't know what could be causing it so not much help here.

Were you able to find the culprit DasReyko?

**Comment by DasReyko** [comment]
Sadly not, I have no idea, even i've shordly made a fresh install of Windows, but still happening only on Firefox.

**Comment by madou** [comment]
I'll have a look when I can. In Japan on holiday ATM :)

**Comment by Pluckerpluck** [comment]
I'm getting this. Pretty sure it's related to Firefox Quantum. Which is their rebuild of a bunch of internals (including their CSS renderer). So older versions (prior to 58) do not have this issue.

What I've noticed is that unlike in other browsers, the embeds linger for about 0.2 seconds after leaving the element they were hovering over. This linger is likely what causes the issue.

So the question is why this might be happening, and it's potentially an issue that should be reported to Firefox if you know what's causing the issue.

(It's worth someone testing with Nightly or Beta if possible, to ensure this hasn't already been fixed).
