### ISSUE TITLE
Stats won't show

### ISSUE THREAD

**Issue by Advanium** [madou/armory-embeds#18]
Hi,

first off thanks for providing this, appreciated!

The stats for f.e. Bifrost won't show on my tests. Here's the HTML I generated.

`<div data-armory-embed="items" data-armory-size="48" data-armory-ids="30698" data-armory-30698-upgrades="24615,24554" data-armory-30698-upgrade-count='{"24615": 1,"24554": 1}' data-armory-30698-infusions="39336,39336" data-armory-30698-stat="161"></div>`

Can you point me to what might be causing this?

**Comment by madou** [comment]
can you give an example codesandbox?

**Comment by stygiansabyss** [comment]
I am seeing the same thing.

Embed Code
```
<div data-armory-embed="items" data-armory-ids="80710" data-armory-80710-skin="4584" data-armory-80710-stat="1153" data-armory-80710-upgrades="24562" data-armory-80710-infusions="49424"></div>
```

Result
![screen shot 2018-06-02 at 10 36 48 am](https://user-images.githubusercontent.com/4187442/40878055-e5467e1e-6650-11e8-9290-8277f37efacb.png)

If it helps at all, I am generating this from API data.  Which for this item returned the following.

```
{#518 ▼
  +"id": 80710
  +"slot": "WeaponA1"
  +"upgrades": array:1 [▼
    0 => 24562
  ]
  +"infusions": array:1 [▼
    0 => 49424
  ]
  +"skin": 4584
  +"stats": {#519 ▼
    +"id": 1153
    +"attributes": {#520 ▼
      +"Power": 108
      +"Precision": 59
      +"ConditionDamage": 108
      +"ConditionDuration": 59
    }
  }
  +"binding": "Account"
}
```

Hope this helps!

**Comment by madou** [comment]
This is fixed.
