### ISSUE TITLE
Weapon skills

### ISSUE THREAD

**Issue by stygiansabyss** [madou/armory-embeds#20]
I'm honestly not sure if this is even possible.  But would it be doable to do weapon skills in an easy to use fashion?  My hope is that we could pass the 1 or 2 weapon IDs to you along with the profession and get the skills returned.  

`data-armory-weapon-ids="78182,78686" data-armory-profession="Revenant"`

or

`data-armory-weapon-ids="78182,78686" data-armory-profession="Elementalist" data-armory-attunement="Water"`

Since these are both swords it would convert that data to the Revenant sword skills.

```
28964
29233
26699
28472
28625
```

The only reason I ask is due to limitations in the API.  In order to get this data with the API as it is, I would have to fetch and store every weapon item my users have in order to know the weapon type.  From there I could easily determine the skills (even the thief combos or ele attunements).  But storing all those items would be insane.

If this is not possible I understand.  Just really hopeful it's doable with the data you already store.

Thanks!

**Comment by madou** [comment]
hi @stygiansabyss,

honestly i'm not really investing much time with the embeds - and this seems like it'd need some backend changes to support what you want? i'm not that up to date with anet apis tbh so not sure what's new there.

if it's just a basic "talk to anet apis and show something" then i'd be more onboard :)

**Comment by stygiansabyss** [comment]
This one would require some logic.  To make it work on my site, I needed to do extra calls to find the weapon type.  Then do logic to figure out skills by combining profession, weapon type and attunement.   Thief skills are probably the hardest due to the 3rd skill being the combo (I imagine weavers are the same, i just dont have one).
