### ISSUE TITLE
How to build the armory-embeds service on my server?

### ISSUE THREAD

**Issue by firsthym** [madou/armory-embeds#36]
Hello Madou,
I am using your JS on my site (https://mists.cn, which old one is mists.co) throught this way:
```
<script async src="https://unpkg.com/armory-embeds@^0.x.x/armory-embeds.js"></script>
```
I am a new player with nodejs, can you tell me how to build armory-embeds.js by myself? I want to make the armory-embeds.js for my wordpress server with Docker.
Thank you!

**Comment by madou** [comment]
hi - you can install the npm package and reference it that way instead?

```
npm i armory-embeds
```

and then grab the script out of node modules

https://www.npmjs.com/package/armory-embeds

**Comment by firsthym** [comment]
Thanks for your replay!
Can I get the GW2 wiki images into my server (or my CDN)? It seems the armory-embeds will request the static resouces. Is there any way that I build the database?

**Comment by madou** [comment]
unfortunately no it uses the gw2 api directly and isn't built to store them in another db

**Comment by firsthym** [comment]
Thank you!
