### ISSUE TITLE
Create Gw2Skin embed

### ISSUE THREAD

**Issue by madou** [madou/armory-embeds#4]

**Comment by stygiansabyss** [comment]
I think this one is done sir.  We can add skins to items now.

**Comment by madou** [comment]
@stygiansabyss what were you thinking?

currently you can already give an item a skin with the item embed (see: https://madou.github.io/armory-embeds/?selectedKind=Items&selectedStory=with%20skin&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel).

this issue was originally around creating a "skin only" embed - it could be done today i just haven't really seen anyone need it.
