### ISSUE TITLE
items with Celestial Stats return '[404] item name'

### ISSUE THREAD

**Issue by DeaJae** [madou/armory-embeds#43]
I know the project isn't getting anymore updates, Maybe someone's already solved it and can point me to what to change in a local version.
Using itemstats to get Celestial stats on a item (such as stat selectable LW trinkets) since Expertise and Concentration stats were added to the stat results in gw2armory rendering '[404] Item name' with no stats listed.
I've looked into working out why, as far as I can tell, its getting stats name properly, but can't find where its trying to reference it to the call or how its piping the attributes in either.
Thanks

**Comment by madou** [comment]
Heya! The API might need to be updated, I'm happy to re-deploy if you'd be interested in contributing? 😄 

API repo: https://github.com/madou/gw2-item-stats-api
Component code repo: https://github.com/madou/armory-component-ui
API calls in the embed: 
- callsite for redux action: https://github.com/madou/armory-component-ui/blob/master/src/components/Gw2Item/index.js#L105 
- rest endpoint callsite: https://github.com/madou/armory-component-ui/blob/master/src/lib/gw2/index.js#L145

**Comment by DeaJae** [comment]
Hi again,
Spotted itemstats API and assumed it just outputted name and numbers, seems like I was wrong.
Used Postman to send some data over, Read will output Celestial's name from ID, Bulk_read responds with 'impossible condition' on all of the celestial's I've tried so far. 
I'm suspecting the issue is in there, so will try to look at it over weekend and put a contribution on the proper repo if I figure it out.
Thanks

**Comment by DeaJae** [comment]
After spending all day getting a server to actually serve gw2-item-stats-api, my idea of a fix worked. Have submitted it to the right repo.

**Comment by madou** [comment]
Where have you submitted it?
