### ISSUE TITLE
Ability the customize the display text of an embed when inline text is shown

### ISSUE THREAD

**Issue by discretize** [madou/armory-embeds#9]
Like "Berserker Sword" instead of "Zojja's Blade" as the visible text, but keep the original tooltip & possible (wiki-)link (both pointing to Zojja's Blade)

**Comment by madou** [comment]
nice idea.

agreed with the naming. the most appropriate would probably be:

- `data-armory-inline-text` for being able to rename the text
- `data-armory-link` for the link

naming things man.
